language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=django==1.4.20
  - DJANGO=django==1.5.12
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.8
  - DJANGO=django==1.8.2
install:
  - pip install $DJANGO
  - pip install -r requirements.txt
# Test behave_django with behave :)
# Skip the failing test case
script: python manage.py behave --tags=~@failing && python tests.py
matrix:
  exclude:
   - python: "3.3"
     env: DJANGO=django==1.4.20
   - python: "3.4"
     env: DJANGO=django==1.4.20
